name: 'GPX merger Action'
description: 'Merge GPX files reccursively'
inputs:
  content-path:
    description: 'The folder where your GPX files can be found'
    required: false
    default: 'content/'
  git-path:
    description: 'The remote address of the repository'
    required: false
    default: ${{ github.server_url }}/${{ github.repository }}.git
  username:
    description: 'Your github username'
    required: false
    default: ${{github.repository_owner}}
  user-token:
    description: 'Your connection token to github'
    required: true
  action:
    description: 'Name of the action (if named)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Inject quarkus-github-action repository credentials
      shell: bash
      run: |
        if [ -f ~/.m2/settings.xml ]; then
          if ! grep -q '<id>quarkus-github-action</id>' ~/.m2/settings.xml; then
            sed -i.bak 's@</servers>@<server><id>quarkus-github-action</id><username>${env.GITHUB_ACTOR}</username><password>${env.GITHUB_TOKEN}</password></server></servers>@' ~/.m2/settings.xml
          fi
        else
          mkdir -p ~/.m2/
          cat <<\EOF > ~/.m2/settings.xml
        <?xml version="1.0"?>
        <settings>
          <servers>
            <server>
              <id>quarkus-github-action</id>
              <username>${env.GITHUB_ACTOR}</username>
              <password>${env.GITHUB_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF
        fi
    - name: Set up JBang
      uses: jbangdev/setup-jbang@main
    - name: Run the action
      id: action
      run: jbang --java 21 --fresh --repos 'quarkus-github-action=https://maven.pkg.github.com/the-cyclist-diary/gpx-merger-action/' --repos 'mavencentral' com.github.thecyclistdiary:gpx-merger-action:1.0.2-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
